version: '3.8'

services:
  optimizer-experiment:
    build: .
    image: curis-optimizer:latest
    container_name: optimizer_experiment
    volumes:
      # Mount results directory to host for easy access - matches v2 script path
      - ./docker_results:/app/fault_injection/optimizer_comparison_results
      # Mount the scripts directory for live code updates (optional)
      - ./fault_injection/scripts:/app/fault_injection/scripts:ro
    environment:
      - PYTHONUNBUFFERED=1
      - TF_CPP_MIN_LOG_LEVEL=2  # Reduce TensorFlow verbosity
    # Uncomment for GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    command: >
      python fault_injection/scripts/test_optimizer_mitigation_v3.py
      --num-experiments 1
      --steps-after-injection 10
      --optimizers adam sgd
    stdin_open: true
    tty: true
