version: '3.8'

services:
  optimizer-experiment:
    build: .
    image: curis-optimizer:latest
    container_name: optimizer_experiment
    volumes:
      # Use named volumes to avoid permission issues
      - fault_injection_optimizer:/app/fault_injection/optimizer_comparison_results
      - fault_injection_results:/app/fault_injection/results
      - fault_injection_output:/app/output
      - fault_injection_checkpoints:/app/checkpoints
    environment:
      - PYTHONUNBUFFERED=1
      - TF_CPP_MIN_LOG_LEVEL=2  # Reduce TensorFlow verbosity
    # Uncomment for GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    command: >
      python fault_injection/scripts/test_optimizer_mitigation_v3.py
      --num-experiments 1
      --steps-after-injection 10
      --optimizers adam sgd
    stdin_open: true
    tty: true

# Define named volumes (Docker-managed, no permission issues)
volumes:
  fault_injection_optimizer:
  fault_injection_results:
  fault_injection_output:
  fault_injection_checkpoints:
